In [1]:
import numpy as np

x = np.array([1,2,3], np.int16)

In [2]:
print(type(x))

<class 'numpy.ndarray'>


In [3]:
y = np.array([[1,2,3], [4, 5, 6]], np.int16)
print(y)

[[1 2 3]
 [4 5 6]]


In [4]:
print(x[:, 0])

IndexError: too many indices for array

In [5]:
print(y[:, 0])

[1 4]


In [6]:
print(y[:, 1])

[2 5]


In [7]:
print(y[:, 2])

[3 6]


In [8]:
print(y[0, :])

[1 2 3]


In [9]:
z = np.array([[[1,2,3], [4, 5, 6]], [[0, -1, -2], [-3, -4, -5]]], np.int16)


In [10]:
print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


# Numpy Ndarray properties

In [15]:
print(z.shape)

print(z.ndim) #number of dimensions

print(z.dtype) #datatype

print(z.size)

print(z.nbytes) #size in memory in terms of  bytes 

(2, 2, 3)
3
int16
12
24


In [16]:
print(z.T) #find transpose

[[[ 1  0]
  [ 4 -3]]

 [[ 2 -1]
  [ 5 -4]]

 [[ 3 -2]
  [ 6 -5]]]


In [17]:
print(z.t)

AttributeError: 'numpy.ndarray' object has no attribute 't'

# Numpy Constants

In [19]:
print(np.inf) #infinity

print(np.NAN) #not a number

print(np.NINF) #negative infinity

print(np.NZERO) #negative zero

print(np.PZERO) #positive zero

print(np.e)

print(np.euler_gamma)

print(np.pi)

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793
