In [1]:
import numpy as np
x = np.random.randint(low = 0, high = 9, size = 10)
print(x)

[0 7 2 7 7 1 2 4 4 5]


In [2]:
y = np.random.rand(3, 3)
print(y)

[[0.56795774 0.04225967 0.93008508]
 [0.07566973 0.63504894 0.76702723]
 [0.90989885 0.167549   0.7478983 ]]
