# Dot Product

In [1]:
import numpy as np
print(np.dot(10, 5))

50


In [2]:
a = np.array([2, 4], np.uint8)
b = np.array([5, 6], np.uint8)
print(np.dot(a, b))

34


In [3]:
a = np.array([[2, 4],[5, 8]], np.uint8)
b = np.array([[5, 6],[9, 3]], np.uint8)
print(np.dot(a, b))

[[46 24]
 [97 54]]


In [4]:
a = np.random.rand(10, 5)
b = np.random.rand(5, 2)
c = np.random.rand(2, 3)
d = np.random.rand(3, 4)
e = np.linalg.multi_dot([a, b, c, d])
print(e)

[[0.76480598 0.44018153 1.07157631 0.61840305]
 [0.70098227 0.40099841 1.02555676 0.6109794 ]
 [0.89481071 0.51373566 1.2762241  0.74642202]
 [1.03656625 0.59618437 1.45956926 0.84549847]
 [0.87501265 0.50172186 1.25945459 0.7415802 ]
 [1.70321673 0.97830441 2.42140992 1.41282458]
 [0.56894333 0.3306355  0.74076853 0.40263956]
 [0.87801294 0.50695913 1.20145665 0.68068926]
 [0.98175237 0.55931843 1.47699849 0.89709624]
 [0.7875314  0.4547475  1.07707913 0.60996806]]


# Vector dot product

In [8]:
a = np.array([1 + 5j, 2 + 3j])
b = np.array([3 + 2j, 4 + 7j])
print(np.vdot(a, b))

(42-11j)


# Inner Product

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([0, 1, 0, 1, 0, 1])
print(np.inner(a, b))

12


In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0, 1, 0], [1, 0, 1]])
print(np.inner(a, b))

[[ 2  4]
 [ 5 10]]


# QR Decomposition

In [12]:
a = np.random.rand(3, 3)
print(a)

[[0.38161344 0.02973296 0.2176402 ]
 [0.11727587 0.52300853 0.54130421]
 [0.75124343 0.9350445  0.33633069]]


In [14]:
q, r = np.linalg.qr(a)
print('q = ', q, '\n\nr = ', r, '\n')
print(np.dot(q, r))

q =  [[-0.44856938  0.67143096 -0.5898864 ]
 [-0.1378525  -0.70409352 -0.69659816]
 [-0.88305277 -0.23115529  0.40839323]] 

r =  [[-0.85073447 -0.91112897 -0.46924462]
 [ 0.         -0.56442378 -0.31274304]
 [ 0.          0.         -0.36809933]] 

[[0.38161344 0.02973296 0.2176402 ]
 [0.11727587 0.52300853 0.54130421]
 [0.75124343 0.9350445  0.33633069]]


# Determinant and solving linear equations

In [15]:
a = np.array([[5, 6], [3, 4]])
print(np.linalg.det(a))

1.9999999999999971


In [17]:
a = np.array([[2, 1, -3], [4, -2, 1], [3, 5, -2]], np.int16)
b = np.array([-4, 9, 5], np.int16)

#ax = b

x = np.linalg.solve(a, b)
print(x)

[2. 1. 3.]


# Linear Algebra with SciPy

In [7]:
import numpy as np
import scipy.linalg

# x = np.arange(9).reshape((3,3))

x = np.array([[24, 25, 26], [27, 28, 29], [30, 31, 32]])
print(x)
print("\n", scipy.linalg.inv(x))

[[24 25 26]
 [27 28 29]
 [30 31 32]]

 [[-1.40737488e+14  2.81474977e+14 -1.40737488e+14]
 [ 2.81474977e+14 -5.62949953e+14  2.81474977e+14]
 [-1.40737488e+14  2.81474977e+14 -1.40737488e+14]]


In [10]:
a = np.array([[2, 1, -3], [4, -2, 1], [3, 5, -2]])
p, l, u = scipy.linalg.lu(a)
#p = permutation matrix
#l = lower component
#u = upper component
print(p)
print(l)
print(u)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.5        0.30769231 1.        ]]
[[ 4.         -2.          1.        ]
 [ 0.          6.5        -2.75      ]
 [ 0.          0.         -2.65384615]]


In [17]:
import numpy as np
A = np.matrix([[1, 1], [2, 4]])
B = np.matrix([[35], [94]])
A_inverse = np.linalg.inv(A)
x = A_inverse * B
print(x)

[[23.]
 [12.]]
