# Array Manipulation Routines

In [2]:
import numpy as np
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [4]:
y = x.reshape((3,2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [5]:
x = np.array([[0,1,2],[3,4,5]], dtype = np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [6]:
y = np.reshape(x, 6)
print(y)

[0 1 2 3 4 5]


In [7]:
print(x)

[[0 1 2]
 [3 4 5]]


In [8]:
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [9]:
print(x)

[[0 1 2]
 [3 4 5]]


In [10]:
y = x.flatten()
print(y)

[0 1 2 3 4 5]


In [11]:
y = x.flatten('C') #row-wise flattening
print(y)

[0 1 2 3 4 5]


In [12]:
y = x.flatten('F') #column-wise flattening also known as fortran order
print(y)

[0 3 1 4 2 5]


# Join multiple arrays

In [13]:
x = np.array([1,2,3], dtype = np.uint8)
y = np.array([4,5,6], dtype = np.uint8)
print(x)
print(y)

[1 2 3]
[4 5 6]


In [14]:
z = np.stack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [15]:
z = np.stack((x,y), axis = 0)
print(z)

[[1 2 3]
 [4 5 6]]


In [16]:
z = np.stack((x,y), axis = -1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [17]:
z = np.stack((x,y), axis = 1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
z = np.dstack((x,y))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [20]:
print(z.shape)

(1, 3, 2)


In [21]:
z = np.hstack((x,y))
print(z)

[1 2 3 4 5 6]


In [22]:
z = np.vstack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [23]:
print(z.shape)

(2, 3)


In [24]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [25]:
a, b, c = np.split(x, 3)
print(a, b, c)

[0 1 2] [3 4 5] [6 7 8]


In [26]:
x = np.random.rand(4, 4, 4)
print(x)

[[[0.20009867 0.2659721  0.73303544 0.40728643]
  [0.02058575 0.47442681 0.43686768 0.80319327]
  [0.4577789  0.37820308 0.96952465 0.28332509]
  [0.30499986 0.64734328 0.51415145 0.15834185]]

 [[0.42441346 0.52464707 0.28666692 0.20847346]
  [0.47388454 0.62245813 0.76886764 0.37407584]
  [0.71438909 0.30498097 0.97150774 0.4023042 ]
  [0.58552504 0.37146214 0.65634612 0.01007376]]

 [[0.35836984 0.3629952  0.93527801 0.40064694]
  [0.07513451 0.17225229 0.83566008 0.06191427]
  [0.02700297 0.9966425  0.31799857 0.35388141]
  [0.22774379 0.31269158 0.80825567 0.10709258]]

 [[0.57519215 0.00734451 0.49480672 0.97691929]
  [0.47076618 0.96184805 0.76594604 0.91215406]
  [0.92700211 0.199001   0.98525101 0.68439102]
  [0.91533212 0.80933693 0.65096164 0.06193033]]]


In [29]:
y, z = np.dsplit(x, 2)
print(y)
print(z)

[[[0.20009867 0.2659721 ]
  [0.02058575 0.47442681]
  [0.4577789  0.37820308]
  [0.30499986 0.64734328]]

 [[0.42441346 0.52464707]
  [0.47388454 0.62245813]
  [0.71438909 0.30498097]
  [0.58552504 0.37146214]]

 [[0.35836984 0.3629952 ]
  [0.07513451 0.17225229]
  [0.02700297 0.9966425 ]
  [0.22774379 0.31269158]]

 [[0.57519215 0.00734451]
  [0.47076618 0.96184805]
  [0.92700211 0.199001  ]
  [0.91533212 0.80933693]]]
[[[0.73303544 0.40728643]
  [0.43686768 0.80319327]
  [0.96952465 0.28332509]
  [0.51415145 0.15834185]]

 [[0.28666692 0.20847346]
  [0.76886764 0.37407584]
  [0.97150774 0.4023042 ]
  [0.65634612 0.01007376]]

 [[0.93527801 0.40064694]
  [0.83566008 0.06191427]
  [0.31799857 0.35388141]
  [0.80825567 0.10709258]]

 [[0.49480672 0.97691929]
  [0.76594604 0.91215406]
  [0.98525101 0.68439102]
  [0.65096164 0.06193033]]]


In [30]:
y, z = np.hsplit(x, 2)
print(y)
print(z)

[[[0.20009867 0.2659721  0.73303544 0.40728643]
  [0.02058575 0.47442681 0.43686768 0.80319327]]

 [[0.42441346 0.52464707 0.28666692 0.20847346]
  [0.47388454 0.62245813 0.76886764 0.37407584]]

 [[0.35836984 0.3629952  0.93527801 0.40064694]
  [0.07513451 0.17225229 0.83566008 0.06191427]]

 [[0.57519215 0.00734451 0.49480672 0.97691929]
  [0.47076618 0.96184805 0.76594604 0.91215406]]]
[[[0.4577789  0.37820308 0.96952465 0.28332509]
  [0.30499986 0.64734328 0.51415145 0.15834185]]

 [[0.71438909 0.30498097 0.97150774 0.4023042 ]
  [0.58552504 0.37146214 0.65634612 0.01007376]]

 [[0.02700297 0.9966425  0.31799857 0.35388141]
  [0.22774379 0.31269158 0.80825567 0.10709258]]

 [[0.92700211 0.199001   0.98525101 0.68439102]
  [0.91533212 0.80933693 0.65096164 0.06193033]]]


In [31]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [32]:
y = np.flip(x, axis = -1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [33]:
y = np.flip(x, axis = 0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [34]:
y = np.flip(x, axis = 1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [35]:
y = np.fliplr(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [36]:
y = np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [37]:
y = np.roll(x, 8)
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [38]:
y = np.rot90(x)
print(y)

[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
